language: node_js
node_js:
  - "10"

dist: "trusty"
sudo: false

cache:
  directories:
    - "node_modules"

install:
  - npm install -g yarn

script:
  - yarn lint
  - yarn build --base-href https://mmaelicke.github.io

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/cv
  repo: mmaelicke/mmaelicke.github.io.git
  on:
    branch: master
