language: node_js
node_js:
  - "9"

dist: "trusty"
sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn global add @angular/cli

script:
  - yarn lint
  - yarn build --base-href https://mmaelicke.github.io

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/cv
  repo: mmaelicke/mmaelicke.github.io.git
  on:
    branch: master
